input {
  gelf {
    port => 12201
  }
}

filter {
  # Docker wraps standard output into the 'message' GELF string.
  # We parse that exact app.py JSON string dynamically here:
  if [message] {
    json {
      source => "message"
      target => "telemetry"
      skip_on_invalid_json => true
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "layoff-risk-telemetry-%{+YYYY.MM.dd}"
  }
  # Print nicely into terminal so we can debug it
  stdout { codec => rubydebug }
}
